import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//${geistSans.variable} ${geistMono.variable}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} antialiased bg-[#fafafa]`}
      >
        {children}
      </body>
    </html>
  );
}
